package com.sakurastudios.lsl

import java.io.BufferedReader
import java.io.InputStreamReader

/**
 * Rich catalogue of LSL built-in functions, constants and events.
 *
 * Loaded once from the packaged resource
 * `/builtins/lsl-builtins-detailed.txt`, which is generated by
 *
 *     ./sakura-lslc/lslc --list-builtins-detailed
 *
 * Each line is a one-line JSON object. Three shapes:
 *
 *     {"k":"fn",    "name":"llSay","ret":"void","params":["integer","string"],"flags":0}
 *     {"k":"const", "name":"TRUE","type":"integer","value":"1"}
 *     {"k":"event", "name":"touch_start","params":[{"type":"integer","name":"total_number"}]}
 *
 * The flags bitfield matches BFN_* from sakura-lslc/src/lsl.h:
 *
 *     BFN_DEPRECATED = 0x1
 *     BFN_GODLY      = 0x2
 *     BFN_EXPERIENCE = 0x4
 *     BFN_MONO_ONLY  = 0x8
 */
object LslBuiltins {

    data class Fn(
        val name: String,
        val ret: String,
        val params: List<String>,
        val flags: Int
    ) {
        val signature: String get() =
            "$ret $name(${params.joinToString(", ")})${if (flags and 0x8 != 0) "   (Mono only)" else ""}"
        val monoOnly: Boolean get() = flags and 0x8 != 0
    }
    data class Const(val name: String, val type: String, val value: String) {
        val signature: String get() = "$type $name = $value"
    }
    data class EvParam(val type: String, val name: String)
    data class Ev(val name: String, val params: List<EvParam>) {
        val signature: String get() =
            "$name(${params.joinToString(", ") { "${it.type} ${it.name}" }})"
    }

    @JvmField val FUNCTIONS: Map<String, Fn>
    @JvmField val CONSTANTS: Map<String, Const>
    @JvmField val EVENTS:    Map<String, Ev>

    @JvmField val FUNCTION_NAMES: List<String>
    @JvmField val CONSTANT_NAMES: List<String>
    @JvmField val EVENT_NAMES:    List<String>

    @JvmField val KEYWORDS: List<String> = listOf(
        "default", "state", "if", "else", "while", "do", "for",
        "return", "jump", "print"
    )
    @JvmField val TYPES: List<String> = listOf(
        "integer", "float", "string", "key",
        "vector", "rotation", "quaternion", "list"
    )

    init {
        val fns    = LinkedHashMap<String, Fn>()
        val consts = LinkedHashMap<String, Const>()
        val evts   = LinkedHashMap<String, Ev>()

        try {
            val stream = LslBuiltins::class.java.getResourceAsStream("/builtins/lsl-builtins-detailed.txt")
            if (stream != null) {
                BufferedReader(InputStreamReader(stream, Charsets.UTF_8)).use { r ->
                    r.lineSequence().forEach { line ->
                        val t = line.trim()
                        if (t.isEmpty() || !t.startsWith("{")) return@forEach
                        when (Json.peek(t, "k")) {
                            "fn"    -> Json.parseFn(t)?.let    { fns[it.name] = it }
                            "const" -> Json.parseConst(t)?.let { consts[it.name] = it }
                            "event" -> Json.parseEvent(t)?.let { evts[it.name] = it }
                        }
                    }
                }
            }
        } catch (_: Exception) {
            // fall through; FUNCTIONS may be empty but the names list will still be set below
        }
        // If empty, fall back to the names-only resource so completion isn't totally dead.
        if (fns.isEmpty()) {
            try {
                val s = LslBuiltins::class.java.getResourceAsStream("/builtins/lsl-builtins.txt")
                if (s != null) {
                    BufferedReader(InputStreamReader(s, Charsets.UTF_8)).use { r ->
                        var bucket = ""
                        r.lineSequence().forEach { raw ->
                            val ln = raw.trim()
                            if (ln.isEmpty()) return@forEach
                            if (ln.startsWith("#")) {
                                bucket = when {
                                    ln.contains("functions") -> "fn"
                                    ln.contains("constants") -> "const"
                                    ln.contains("events") -> "event"
                                    else -> ""
                                }
                                return@forEach
                            }
                            when (bucket) {
                                "fn"    -> fns[ln]    = Fn(ln, "?", emptyList(), 0)
                                "const" -> consts[ln] = Const(ln, "?", "")
                                "event" -> evts[ln]   = Ev(ln, emptyList())
                            }
                        }
                    }
                }
            } catch (_: Exception) {}
        }

        FUNCTIONS = fns
        CONSTANTS = consts
        EVENTS    = evts
        FUNCTION_NAMES = fns.keys.toList()
        CONSTANT_NAMES = consts.keys.toList()
        EVENT_NAMES    = evts.keys.toList()
    }

    @JvmStatic fun looksLikeBuiltinFunction(name: String): Boolean =
        name.length >= 3 && name[0] == 'l' && name[1] == 'l' && name[2].isUpperCase()

    @JvmStatic fun isFunction(name: String): Boolean = FUNCTIONS.containsKey(name)
    @JvmStatic fun isConstant(name: String): Boolean = CONSTANTS.containsKey(name)
    @JvmStatic fun isEvent(name: String):    Boolean = EVENTS.containsKey(name)
    @JvmStatic fun isType(name: String):     Boolean = TYPES.contains(name)
    @JvmStatic fun isKeyword(name: String):  Boolean = KEYWORDS.contains(name)
}

/** Tiny non-throwing JSON peek/parse — enough for our one-line records. */
private object Json {
    /** Read the value of a top-level string field "key":"value". */
    fun peek(line: String, key: String): String? {
        val pat = "\"$key\":\""
        val i = line.indexOf(pat); if (i < 0) return null
        val s = i + pat.length
        val e = line.indexOf('"', s); if (e < 0) return null
        return line.substring(s, e)
    }
    fun peekInt(line: String, key: String): Int? {
        val pat = "\"$key\":"
        val i = line.indexOf(pat); if (i < 0) return null
        val s = i + pat.length
        var j = s
        while (j < line.length && (line[j].isDigit() || line[j] == '-')) j++
        return line.substring(s, j).toIntOrNull()
    }
    /** Strings inside a JSON array of strings: ["integer","string"]. */
    private fun stringArrayUnder(line: String, key: String): List<String> {
        val pat = "\"$key\":["
        val i = line.indexOf(pat); if (i < 0) return emptyList()
        var j = i + pat.length
        val out = mutableListOf<String>()
        while (j < line.length) {
            while (j < line.length && line[j] == ' ') j++
            if (j >= line.length || line[j] == ']') break
            if (line[j] != '"') { j++; continue }
            val s = ++j
            while (j < line.length && line[j] != '"') {
                if (line[j] == '\\' && j+1 < line.length) j++
                j++
            }
            out += line.substring(s, j)
            if (j < line.length) j++
            if (j < line.length && line[j] == ',') j++
        }
        return out
    }
    /** Array of {"type":..,"name":..} entries. */
    private fun paramObjs(line: String): List<LslBuiltins.EvParam> {
        val pat = "\"params\":["
        val i = line.indexOf(pat); if (i < 0) return emptyList()
        var j = i + pat.length
        val out = mutableListOf<LslBuiltins.EvParam>()
        var depth = 1
        while (j < line.length && depth > 0) {
            val ch = line[j]
            if (ch == '[') depth++
            else if (ch == ']') { depth--; if (depth == 0) break }
            else if (ch == '{') {
                // find closing brace
                val s = j
                var d = 1; j++
                while (j < line.length && d > 0) {
                    val c = line[j]
                    if (c == '{') d++
                    else if (c == '}') d--
                    j++
                }
                val obj = line.substring(s, j)
                val t = peek(obj, "type") ?: continue
                val n = peek(obj, "name") ?: ""
                out += LslBuiltins.EvParam(t, n)
                continue
            }
            j++
        }
        return out
    }

    fun parseFn(line: String): LslBuiltins.Fn? {
        val name = peek(line, "name") ?: return null
        val ret  = peek(line, "ret") ?: "void"
        val params = stringArrayUnder(line, "params")
        val flags = peekInt(line, "flags") ?: 0
        return LslBuiltins.Fn(name, ret, params, flags)
    }
    fun parseConst(line: String): LslBuiltins.Const? {
        val name = peek(line, "name") ?: return null
        val type = peek(line, "type") ?: "?"
        val value = peek(line, "value") ?: ""
        return LslBuiltins.Const(name, type, value)
    }
    fun parseEvent(line: String): LslBuiltins.Ev? {
        val name = peek(line, "name") ?: return null
        return LslBuiltins.Ev(name, paramObjs(line))
    }
}
